# Generated by Django 2.2.7 on 2019-12-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatMessages', '0002_auto_20191211_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='owner',
        ),
    ]
